In [1]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

2025-04-11 03:57:03.835880: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1744343824.212736      31 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744343824.316486      31 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

Find word count -> frequency of each word

In [5]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

Find number of Rows/ sentences in the document

In [6]:
tokenizer.document_count

10

Generate the sequences of te sentenes

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

above sentences ar not in same length - apply padding

In [8]:
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post') # post-> add 0 at the end f ech senence
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [9]:
#import dataset
from tensorflow.keras.datasets import imdb
# import model type
from tensorflow.keras import Sequential
#inport various layes for the rnn
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [10]:
#split data into training and testing.
(x_train, y_train),(x_test, y_test) = imdb.load_data();

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [11]:
x_train[0]



[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [12]:
from tensorflow.keras.utils import pad_sequences
x_train = pad_sequences(x_train, padding='post',maxlen=50)
x_test  = pad_sequences(x_test, padding='post',maxlen=50)

In [13]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))# 32-> nuerons
model.add(Dense(1,activation='sigmoid')) #

I0000 00:00:1744343846.945397      31 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13942 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1744343846.946569      31 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13942 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train, y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5


I0000 00:00:1744343851.383309      93 service.cc:148] XLA service 0x3da01080 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1744343851.384894      93 service.cc:156]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
I0000 00:00:1744343851.384913      93 service.cc:156]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
I0000 00:00:1744343851.812313      93 cuda_dnn.cc:529] Loaded cuDNN version 90300


 27/782 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5268 - loss: 0.8425

I0000 00:00:1744343852.780631      93 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5085 - loss: 0.7160 - val_accuracy: 0.5072 - val_loss: 0.6942
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5096 - loss: 0.6931 - val_accuracy: 0.5000 - val_loss: 0.6946
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5089 - loss: 0.6925 - val_accuracy: 0.5029 - val_loss: 0.6946
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5098 - loss: 0.6928 - val_accuracy: 0.5023 - val_loss: 0.6948
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5008 - loss: 0.6932 - val_accuracy: 0.5073 - val_loss: 0.6935


**USING EMBEDDING for textual data conversion into numerical vectors**

**----------------------------------------------**

In [16]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

tokenizer.fit_on_texts(docs)

len(tokenizer.word_index)

sequences = tokenizer.texts_to_sequences(docs)
sequences

from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5)) #(vocab-length, dimenstion(hyperparam), )
# dimention of dese vector
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.compile('adam','accuracy')

pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step
[[[ 0.02007245  0.01648012]
  [ 0.03361691  0.02388265]
  [-0.02311273  0.00661365]
  [-0.02311273  0.00661365]
  [-0.02311273  0.00661365]]

 [[ 0.03361691  0.02388265]
  [ 0.03361691  0.02388265]
  [-0.02311273  0.00661365]
  [-0.02311273  0.00661365]
  [-0.02311273  0.00661365]]

 [[-0.02667577  0.02074039]
  [-0.02667577  0.02074039]
  [-0.02941169 -0.02751321]
  [-0.02311273  0.00661365]
  [-0.02311273  0.00661365]]

 [[-0.02062063  0.00769724]
  [ 0.02968309  0.00298967]
  [-0.02062063  0.00769724]
  [ 0.03361691  0.02388265]
  [-0.02062063  0.00769724]]

 [[ 0.04712621  0.00104374]
  [ 0.04898902  0.02580375]
  [ 0.03716317 -0.00584736]
  [ 0.01826343 -0.00147133]
  [-0.02311273  0.00661365]]

 [[-0.02918126 -0.01774829]
  [-0.02918126 -0.01774829]
  [-0.02311273  0.00661365]
  [-0.02311273  0.00661365]
  [-0.02311273  0.00661365]]

 [[-0.02343448 -0.02702949]
  [-0.02343448 -0.02702949]
  [-0.02311273  0.00661365]
  [-0.02311273  0.0066136